GET http://localhost:7007/api/auth/demo
###
POST http://localhost:7007/api/auth/register

{
    "username": "test",
    "password": "test"
}
###
POST http://localhost:7007/api/auth/login

{
    "username": "test",
    "password": "test"
}
###
GET http://localhost:7007/api/protected/user_demo
Authorization: Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjk4MzE1OTE5LCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InRlc3QifQ.a0FuX_AxsHNc7QGkKHupfE0yL2PDMzq3NRFsYuHxnXQ
###
GET http://localhost:7007/api/protected/admin_demo
Authorization: Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjk3MDQxNjQ4LCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InRlc3QifQ.8b7o0ADrpO11iBfIkyb9RHvgZBD6MXf8xoy9DIG_j6o
###
POST http://104.248.29.155:7007/api/auth/login

    {
        "username": "user1",
        "password": "test123"
    }

###
GET http://104.248.29.155:7007/api/protected/user_demo
Authorization: Baerer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMtSGFydG1hbm4iLCJzdWIiOiJ1c2VyMSIsImV4cCI6MTY5ODM0NjM0Nywicm9sZXMiOiJhZG1pbix1c2VyIiwidXNlcm5hbWUiOiJ1c2VyMSJ9.ktviB3A3wLXvW9KtvfObixiEO3xccfsbNN9TXKWKOoM

###